import './globals.css'
import { Inter } from 'next/font/google'
import { Provider } from '../components/Client-provider'
import { auth } from '../lib/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Check your bees',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>{children}</Provider>
      </body>
    </html>
  )
}
